### ISSUE TITLE
[bug] when alt-tabbed out of game, can't tab back eldenring.exe process

### ISSUE THREAD

**Issue by jrson83** [soarqin/EROverlay#1]
Thanks for the great mod, I love it. After playing some days with it, I noticed that when alt-tabbed out of game, I can't tab back eldenring.exe process. When I press alt-tab, switching between processes, the elden ring process does not come active when selecting it. This happens everytime I tab out the game.

I'm on windows 11 (Atlas OS), playing with steam, but replaced the start_protected_game.exe with eldenring.exe to play offline. Using `EldenModLoader-117-3-2`.

**Comment by s-vivien** [comment]
I've got the same issue :/

**Comment by jrson83** [comment]
@s-vivien I thought it might be related to [EldenModLoader](https://www.nexusmods.com/eldenring/mods/117), but I have the same issue using the standalone .exe or [ModEngine2](https://github.com/soulsmods/ModEngine2).

**Comment by soarqin** [comment]
I think this is resolved in later version, I have also fixed the display issue while change the display resolution in options.
Closing this, feel free to reopen this if you meet the problem again.
