### ISSUE TITLE
How to get the data/zhocn.json?

### ISSUE THREAD

**Issue by a361570441** [soarqin/EROverlay#3]
Hello, I am very interested in your project, especially the part about event_flag, but I don't quite understand how the boss's ID in event_flag matches the value of event_flag? (For example, [Morgott, the Omen King](“恶兆王”蒙葛特） corresponds to 0x152DC7 . How did you find this matching relationship like from Deathbird_LimgraveAddr to 0xA0E1F? I would be grateful if you would disclose it.
I tried unpacking the game file but found nothing about the address except the boss's id.

**Comment by a361570441** [comment]
您似乎看得懂中文！实在是太好了，看起来这些数据都是通过origin.txt得到的 请问您是怎么得到origin.txt的？我是一名工具开发者，想要为黄金树之影做准备，请您不吝赐教！！

**Comment by a361570441** [comment]
+ Bloodhound Knight Darriwil|Forlorn Hound Evergaol:28,B154E,7,1 这样的数据对我非常有意义！但是看到您在另外一个项目中改为了event_flag_id作为替代，请问您还有办法生成类似于B154E,7, 这种偏移量+bit的方法吗？

**Comment by soarqin** [comment]
用event_flag_id是为了方便使用event flag logger(SoulSplitter)来查新boss的flag，可以看https://github.com/soarqin/EROverlay/blob/0bbd1eceacf2ed99124eefaafc96a5ed59b7f378/src/api.cpp#L50这个函数来获取flag id对应的地址，如果需要内存地址，可以通过对数据列表调用这个函数来获取。
