### ISSUE TITLE
Font loading is bit of confusing

### ISSUE THREAD

**Issue by Lorie-Capella** [soarqin/EROverlay#4]
there r just suggestions:
1. make it able to load system fonts
2. font loading is bit confusing, as it only loads ttf at /data folder, just write this in the description. i tried to use font family name but failed, so i think itz necessary to indicate that config file only accepts font path name, not font family name.
3. it would be better if specific charset should use font in specific folder, its possible to embed certain lang's font to its folder. so normally user dont have to copy their font to the path, or just use a suitable system font

**Comment by soarqin** [comment]
Loading from system font folder is implemented in unreleased commits.
If default fonts are about to be used, I need a default fonts list for windows in different languages.

**Comment by soarqin** [comment]
Should be okay in 1.4.0, sorry for late to close this.
